// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRS9yr75y5VONfexf10yW9gHQ3JWanDE',
    appId: '1:232077585270:web:053854a24a480e0a802857',
    messagingSenderId: '232077585270',
    projectId: 'hejitechllc',
    authDomain: 'hejitechllc.firebaseapp.com',
    storageBucket: 'hejitechllc.firebasestorage.app',
    measurementId: 'G-74LJJDLV53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zW6r3f8Z6jR8-aNSoY-OTjCLJQiCmHw',
    appId: '1:232077585270:android:6acf62a1ffe94382802857',
    messagingSenderId: '232077585270',
    projectId: 'hejitechllc',
    storageBucket: 'hejitechllc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZfVVqP1ru5tbJNmCTgVHWfTdlimR7Vw',
    appId: '1:232077585270:ios:a787bcc3178b31ef802857',
    messagingSenderId: '232077585270',
    projectId: 'hejitechllc',
    storageBucket: 'hejitechllc.firebasestorage.app',
    iosBundleId: 'com.hejitech.hejitechHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZfVVqP1ru5tbJNmCTgVHWfTdlimR7Vw',
    appId: '1:232077585270:ios:a787bcc3178b31ef802857',
    messagingSenderId: '232077585270',
    projectId: 'hejitechllc',
    storageBucket: 'hejitechllc.firebasestorage.app',
    iosBundleId: 'com.hejitech.hejitechHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRS9yr75y5VONfexf10yW9gHQ3JWanDE',
    appId: '1:232077585270:web:04d57a20822c74c7802857',
    messagingSenderId: '232077585270',
    projectId: 'hejitechllc',
    authDomain: 'hejitechllc.firebaseapp.com',
    storageBucket: 'hejitechllc.firebasestorage.app',
    measurementId: 'G-J565BRX6HN',
  );
}
